version: '3.12'
services:
  db:
    image: postgres:latest
    container_name: market_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: market_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://root:root@db:5432/market_management
    command: flask run --host=0.0.0.0

volumes:
  postgres_data:
