services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: projetoms
    volumes:
      - data_db:/var/lib/postgresql/data
    
volumes:
  data_db:
